### ISSUE TITLE
Fehlende Erklärung bei 2.1 7

### ISSUE THREAD

**Issue by Jojo-05** [uvraj/ES_QA#4]
**Frage:** Was versteht man in der Lichttechnik unter einem kontinuierlichen Spektrum?

=> nicht wirklich beantwortet. daher bitte folgende Bilder ergänzen:
7: 
![image](https://user-images.githubusercontent.com/85748312/234203328-16a266c7-8627-43d5-9553-773d806fc3d4.png)

und der Vollständigkeit halber auch:
8: 
![image](https://user-images.githubusercontent.com/85748312/234203414-2b565853-6744-40fe-8ddf-fd087803ad2e.png)

**Comment by Alx-179** [comment]
Bilder beantworten die Frage auch nicht

**Comment by Jojo-05** [comment]
vergiss es, machs ma selbst
